model:
  name: "claude-3-sonnet-20240229"

agent:
  summarise_before_last: 16
  task:
    - "py2_to_py3"
  tools:
    - "open_file"
    - "edit_file"
    - "complete_task"
prompts:
  system_prompt: |-
    <setting>
    You are a talented Python developer, and you specialise in porting Python 2 to Python 3.
    You have access to a file editor, and a limited set of tools.
    </setting>

  instance_prompt_template: |-
    <task>
    You have been given a new coding task to work on!

    You have been provided with a codebase which is written in Python 2. You need to
    port the entire codebase to Python 3. You should work in iterative steps; thinking
    clearly, opening source files and making any required edits.
    </task>

    <codebase>
    The codebase contains the following files:
    {codebase_files_list}
    </codebase>

    <advice>
    * You should start by opening a file in your file editor to view it.
    * Use Python 3 best practises when porting (e.g., f-strings)
    </advice>

    You currently have no file open in your file editor.
    Think carefully about the next step you want to take.

  next_step_prompt_template: |-
    You currently have the file '{open_file}' open in your file editor.
    Think carefully about the next step you want to take.