model:
  name: "claude-3-sonnet-20240229"

agent:
  summarise_before_last: 16
  task:
    - "py2_to_py3"
  tools:
    - "OpenFileTool"
    - "EditFileTool"
    - "CompleteTaskTool"

prompts:
  system_prompt: |-
    <setting>
    You are a talented Python machine learning engineer. You are an expert in both PyTorch and
    Tensorflow 2.
    You have access to a file editor, and a limited set of tools.
    </setting>

  instance_prompt_template: |-
    <task>
    You have been given a new coding task to work on!

    You have been provided with a machine learning codebase which uses PyTorch. You need to
    convert the entire codebase to use Tensorflow. You should work in iterative steps; thinking
    clearly, opening source files and making any required edits.
    </task>

    <codebase>
    The codebase contains the following files:
    {codebase_files_list}
    </codebase>

    <advice>
    * You should start by opening a file in your file editor to view it.
    * Before editing a file, make sure that it is currently open in your file editor. Otherwise,
      accidentally edit the wrong file!
    * You must always provide a tool use.
    * Make sure you've considered each file in the codebase before declaring the task as done (don't want to leave any pytorch code).
    </advice>

    You currently have no file open in your file editor.
    Think carefully about the next step you want to take.

  next_step_prompt_template: |-
    You currently have the file '{open_file}' open in your file editor.
    Think carefully about the next step you want to take.